### ISSUE TITLE
Add deploy stage to CI

### ISSUE THREAD

**Issue by Chesire** [Chesire/Eden#21]
Add something to the github actions so that there is a sample deploy stage. As part of this, the readme should be updated to mention to add the required secrets.

```
  deploy:
    if: startsWith(github.ref, 'refs/tags/*')
    needs: [test, analyze]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 1.8
    - name: Fetch tags
      run: git fetch origin 'refs/tags/*:refs/tags/*'
    - name: run assembleDebug
      run: ./gradlew assembleDebug
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Deploy
      run: ./gradlew bintrayUpload -PbintrayUser=${{ secrets.BINTRAY_USER_ID }} -PbintrayKey=${{ secrets.BINTRAY_API_KEY }} -PpublishVersion=${{ env.RELEASE_VERSION }} -PdryRun=false
```
