### ISSUE TITLE
Change from using Danger action

### ISSUE THREAD

**Issue by Chesire** [Chesire/Eden#96]
Remove the usage of the Danger action, and instead run Danger manually.
```
    - uses: actions/setup-ruby@v1.1.3
      with:
        ruby-version: '2.6'
    - uses: actions/cache@v2.1.5
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: bundle install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --without=documentation --jobs 4 --retry 3
    - name: danger
      run: bundle exec danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
```
